# Generated by Django 3.2 on 2024-01-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TariffDescription',
        ),
    ]
