# Generated by Django 3.2 on 2024-01-23 16:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_delete_tariffdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='work_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], max_length=13, verbose_name='Рабочие дни'),
        ),
    ]
