# Generated by Django 3.2 on 2024-01-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_service_work_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('my_order',), 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('my_order',), 'verbose_name': 'Категория сервисов', 'verbose_name_plural': 'Категории сервисов'},
        ),
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'ordering': ('my_order',), 'verbose_name': 'Подкатегория сервисов', 'verbose_name_plural': 'Подкатегории сервисов'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='service',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AlterField(
            model_name='business',
            name='first_phone_number',
            field=models.CharField(help_text='+996XXXXXXXXX или +0312XXXXXX', max_length=30, verbose_name='Первый рабочий номер'),
        ),
        migrations.AlterField(
            model_name='business',
            name='second_phone_number',
            field=models.CharField(blank=True, help_text='+996XXXXXXXXX или +0312XXXXXX', max_length=30, null=True, verbose_name='Второй рабочий номер'),
        ),
        migrations.AlterField(
            model_name='business',
            name='third_phone_number',
            field=models.CharField(blank=True, help_text='+996XXXXXXXXX или +0312XXXXXX', max_length=30, null=True, verbose_name='Третий рабочий номер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='first_phone_number',
            field=models.CharField(help_text='+996XXXXXXXXX или +0312XXXXXX', max_length=30, verbose_name='Первый рабочий номер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='second_phone_number',
            field=models.CharField(blank=True, help_text='+996XXXXXXXXX или +0312XXXXXX', max_length=30, null=True, verbose_name='Второй рабочий номер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='third_phone_number',
            field=models.CharField(blank=True, help_text='+996XXXXXXXXX или +0312XXXXXX', max_length=30, null=True, verbose_name='Третий рабочий номер'),
        ),
    ]
