# Generated by Django 3.2 on 2024-02-11 10:54

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20240131_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayboxPaymentTransaction',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID Paybox')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма')),
                ('currency', models.CharField(max_length=100, verbose_name='Валюта')),
                ('payment_date', models.DateTimeField(verbose_name='Дата и время совершения платежа')),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='business',
            name='first_phone_number',
            field=models.CharField(help_text='+996XXXXXXXXX или +996312XXXXXX', max_length=30, verbose_name='Первый рабочий номер'),
        ),
        migrations.AlterField(
            model_name='business',
            name='second_phone_number',
            field=models.CharField(blank=True, help_text='+996XXXXXXXXX или +996312XXXXXX', max_length=30, null=True, verbose_name='Второй рабочий номер'),
        ),
        migrations.AlterField(
            model_name='business',
            name='third_phone_number',
            field=models.CharField(blank=True, help_text='+996XXXXXXXXX или +996312XXXXXX', max_length=30, null=True, verbose_name='Третий рабочий номер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='first_phone_number',
            field=models.CharField(help_text='+996XXXXXXXXX или +996312XXXXXX', max_length=30, verbose_name='Первый рабочий номер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.custom_upload_path, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='service',
            name='second_phone_number',
            field=models.CharField(blank=True, help_text='+996XXXXXXXXX или +996312XXXXXX', max_length=30, null=True, verbose_name='Второй рабочий номер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='third_phone_number',
            field=models.CharField(blank=True, help_text='+996XXXXXXXXX или +996312XXXXXX', max_length=30, null=True, verbose_name='Третий рабочий номер'),
        ),
        migrations.CreateModel(
            name='PayboxOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('failed', 'Отклонено'), ('success', 'Успешно'), ('not_completed', 'Не завершен')], max_length=20, verbose_name='Статус')),
                ('description', models.TextField(default='')),
                ('redirect_url', models.URLField(blank=True, null=True, verbose_name='Ссылка для оплаты')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paybox_transactions', to='business.business', verbose_name='Бизнес')),
                ('paybox_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paybox_order', to='business.payboxpaymenttransaction')),
            ],
            options={
                'verbose_name': 'Транзакция Paybox',
                'verbose_name_plural': 'Транзакции Paybox',
                'ordering': ('-created_at',),
            },
        ),
    ]
