# Generated by Django 3.2 on 2024-02-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20240211_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payboxorder',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='payboxorder',
            name='paybox_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paybox_order', to='business.payboxpaymenttransaction', verbose_name='Paybox ID платежа'),
        ),
        migrations.AlterField(
            model_name='payboxorder',
            name='status',
            field=models.CharField(choices=[('init', 'Инициализирован'), ('failed', 'Отклонено'), ('success', 'Успешно')], default='init', max_length=20, verbose_name='Статус'),
        ),
    ]
