# Generated by Django 3.2 on 2024-02-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20240212_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payboxpaymenttransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payboxpaymenttransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payboxpaymenttransaction',
            name='payment_date',
        ),
    ]
