# Generated by Django 3.2 on 2024-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20240220_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('my_order',), 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='is_first',
        ),
        migrations.AddField(
            model_name='tariff',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
    ]
