# Generated by Django 3.2 on 2024-04-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20240328_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='business.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='business.servicecategory', verbose_name='Категория сервиса'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Если выбрана подкатегория, то сервис будет отображаться только в подкатегории. В категории сервиса она отображаться не будет', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='business.servicesubcategory', verbose_name='Подкатегория сервиса'),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='business.servicecategory', verbose_name='Категория'),
        ),
    ]
