# Generated by Django 3.2 on 2024-05-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20240516_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('my_order',), 'verbose_name': 'Категория магазина', 'verbose_name_plural': 'Категории магазинов'},
        ),
    ]
