# Generated by Django 3.2 on 2024-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_servicecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
