# Generated by Django 3.2 on 2024-06-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_tariff_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(to='business.ServiceCategory', verbose_name='Категории магазинов'),
        ),
    ]
