# Generated by Django 3.2 on 2024-06-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceviewlog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.servicecategory', verbose_name='категория сервиса'),
        ),
    ]
