# Generated by Django 3.2 on 2023-11-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Новый номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Код подтверждения'),
        ),
    ]
