# Generated by Django 3.2 on 2024-01-11 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
        ('car', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('condition_of_part', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=20, verbose_name='Состояние запчасти')),
                ('difference', models.CharField(choices=[('original', 'Оригинал'), ('analogue', 'Аналог')], max_length=20, verbose_name='Отличие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('availability', models.CharField(choices=[('in_stock', 'В наличии'), ('to_order', 'Под заказ')], max_length=20, verbose_name='Наличие')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='business.business', verbose_name='Бизнес')),
                ('part_manufacturer_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='car.partmanufacturercountry', verbose_name='Страна производитель')),
            ],
            options={
                'verbose_name': 'Ответ на заявку',
                'verbose_name_plural': 'Ответы на заявку',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='car.car', verbose_name='Машина')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='car.part', verbose_name='Запчасть')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request', to='info.region', verbose_name='Регион')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.custom_upload_path, verbose_name='Изображение')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='purchase_request.purchaserequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Изображение для заявки',
                'verbose_name_plural': 'Изображения для заявки',
            },
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.custom_upload_path, verbose_name='Изображение')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='purchase_request.offer', verbose_name='Ответ на заявку')),
            ],
            options={
                'verbose_name': 'Изображение для ответа на заявку',
                'verbose_name_plural': 'Изображения для ответа на заявку',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='purchase_request.purchaserequest', verbose_name='Заявка'),
        ),
    ]
