# Generated by Django 3.2 on 2024-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0002_auto_20240213_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
