# Generated by Django 3.2 on 2024-02-28 17:18

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_mileage'),
        ('purchase_request', '0003_auto_20240222_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='car.carbody', verbose_name='Кузов'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.custom_upload_path, verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='car.cardrive', verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='engine',
            field=models.CharField(blank=True, choices=[('gasoline', 'Бензин'), ('gas', 'Газ'), ('gasoline/gas', 'Бензин/газ'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], max_length=15, null=True, verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='engine_displacement',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to='car.carmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('variator', 'Вариатор'), ('robot', 'Робот')], max_length=15, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Год выпуска'),
        ),
    ]
