# Generated by Django 3.2 on 2024-02-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0004_auto_20240228_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='car',
        ),
    ]
