# Generated by Django 3.2 on 2024-04-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20240407_0001'),
        ('info', '0003_auto_20240204_2226'),
        ('purchase_request', '0005_remove_purchaserequest_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='part_manufacturer_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='car.partmanufacturercountry', verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='car.carbody', verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='car.cardrive', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='car.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='car.part', verbose_name='Запчасть'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='info.region', verbose_name='Регион'),
        ),
    ]
