# Generated by Django 3.2 on 2024-05-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20240407_0001'),
        ('purchase_request', '0007_auto_20240503_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='availability',
            field=models.CharField(blank=True, choices=[('in_stock', 'В наличии'), ('to_order', 'Под заказ')], max_length=20, null=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='condition_of_part',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=20, null=True, verbose_name='Состояние запчасти'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='difference',
            field=models.CharField(blank=True, choices=[('original', 'Оригинал'), ('analogue', 'Аналог')], max_length=20, null=True, verbose_name='Отличие'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='part_manufacturer_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='car.partmanufacturercountry', verbose_name='Страна производитель'),
        ),
    ]
