# Generated by Django 3.2 on 2024-05-30 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_request', '0008_auto_20240522_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
