# Generated by Django 3.2 on 2024-06-12 09:49

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0009_purchaserequest_viewed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(max_length=60, verbose_name='Текст')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Стоимость')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=utils.custom_upload_path, verbose_name='Иконка')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Тип заявок',
                'ordering': ['my_order'],
            },
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='vin_code',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN код'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_request.purchaserequesttype', verbose_name='Тип заявки'),
        ),
    ]
