# Generated by Django 3.2 on 2024-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0010_auto_20240612_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='engine_displacement',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Объем'),
        ),
    ]
