# Generated by Django 3.2 on 2024-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='for_business',
            field=models.BooleanField(default=False),
        ),
    ]
