# Generated by Django 3.2 on 2024-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
