# Generated by Django 3.2 on 2024-08-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20240809_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='part_category',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, choices=[('in_stock', 'В наличии'), ('to_order', 'Под заказ')], max_length=20, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition_of_part',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=20, null=True, verbose_name='Состояние запчасти'),
        ),
        migrations.AddField(
            model_name='product',
            name='difference',
            field=models.CharField(blank=True, choices=[('original', 'Оригинал'), ('analogue', 'Аналог')], max_length=20, null=True, verbose_name='Отличие'),
        ),
    ]
