# Generated by Django 3.2 on 2024-08-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20240809_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
