# Generated by Django 3.2 on 2024-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['my_order'], 'verbose_name': 'Акция от партнера', 'verbose_name_plural': 'Акции от партнера'},
        ),
        migrations.AlterModelOptions(
            name='promotionalcodesanddiscount',
            options={'ordering': ['my_order'], 'verbose_name': 'Промокоды и скидки', 'verbose_name_plural': 'Промокоды и скидки'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['my_order'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AddField(
            model_name='banner',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='promotionalcodesanddiscount',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='region',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
    ]
