# Generated by Django 3.2 on 2024-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20240204_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='sub_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок'),
        ),
    ]
