# Generated by Django 3.2 on 2024-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20240516_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_version', models.CharField(max_length=255, verbose_name='Версия приложения')),
                ('android_force_update', models.BooleanField(default=False, verbose_name='Принудительное обновление')),
                ('ios_version', models.CharField(max_length=255, verbose_name='Версия приложения')),
                ('ios_force_update', models.BooleanField(default=False, verbose_name='Принудительное обновление')),
            ],
            options={
                'verbose_name': 'Управление версией приложения',
            },
        ),
    ]
