# Generated by Django 3.2 on 2024-06-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_versioncontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество посещений'),
        ),
    ]
