# Generated by Django 3.2 on 2024-06-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_banner_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalcodesanddiscount',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество переходов'),
        ),
    ]
