# Generated by Django 3.2 on 2024-01-23 06:00

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='icon',
            field=models.ImageField(null=True, upload_to=utils.custom_upload_path, verbose_name='Иконка'),
        ),
    ]
