# Generated by Django 3.2 on 2024-01-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carcategory_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbody',
            options={'ordering': ('my_order',), 'verbose_name': 'Кузов', 'verbose_name_plural': 'Кузова'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'ordering': ('my_order',), 'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марки автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'ordering': ('my_order',), 'verbose_name': 'Категория авто', 'verbose_name_plural': 'Категории авто'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('my_order',), 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('my_order',), 'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.AlterModelOptions(
            name='partmanufacturercountry',
            options={'ordering': ('my_order',), 'verbose_name': 'Страна производитель запчасти', 'verbose_name_plural': 'Страны производители запчасти'},
        ),
        migrations.AddField(
            model_name='carbody',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='carcategory',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='part',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='partmanufacturercountry',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Очередь'),
        ),
    ]
