# Generated by Django 3.2 on 2024-02-10 06:28

from django.db import migrations, models
import django.db.models.deletion



def car_driver_to_none(apps, schema_editor):
    Car = apps.get_model('car', 'Car')
    Car.objects.all().update(drive=None)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20240206_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Привод',
                'verbose_name_plural': 'Приводы',
                'ordering': ('my_order',),
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('front_wheel', 'Передний привод'), ('rear_wheel', 'Задний привод'), ('four_wheel', 'Полный привод')], max_length=15, null=True, verbose_name='Привод'),
        ),
        migrations.RunPython(car_driver_to_none, reverse_code=reverse_func),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='cars', to='car.cardrive',
                                    verbose_name='Привод'),
        ),
    ]
