# Generated by Django 3.2 on 2024-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='category',
            field=models.ManyToManyField(related_name='car_brands', to='car.CarCategory', verbose_name='Категория авто'),
        ),
    ]
