# Generated by Django 3.2 on 2024-04-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_carbrand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='car.carbody', verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='car.cardrive', verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='car.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_models', to='car.carbrand', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_models', to='car.carcategory', verbose_name='Категория авто'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='car.partcategory', verbose_name='Категория'),
        ),
    ]
